name: CI Karsajobs Backend

on:
  push:
    branches: [ "main", "karsajobs" ]
  pull_request:
    branches: [ "main", "karsajobs" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Download Dependencies
        run: go mod download

      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017
          MONGO_HOST: localhost
          MONGO_PORT: 27017
        run: go test -v ./...

      - name: Build Project
        run: go build ./...