name: CI Karsajobs Backend

on:
  push:
    branches: ["main", "karsajobs"]
  pull_request:
    branches: ["main", "karsajobs"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build ./...